// Code generated by ent, DO NOT EDIT.

package pullrequest

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the pullrequest type in the database.
	Label = "pull_request"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPullRequestName holds the string denoting the pull_request_name field in the database.
	FieldPullRequestName = "pull_request_name"
	// FieldAuthorID holds the string denoting the author_id field in the database.
	FieldAuthorID = "author_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldAssignedReviewers holds the string denoting the assigned_reviewers field in the database.
	FieldAssignedReviewers = "assigned_reviewers"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldMergedAt holds the string denoting the merged_at field in the database.
	FieldMergedAt = "merged_at"
	// EdgeAuthor holds the string denoting the author edge name in mutations.
	EdgeAuthor = "author"
	// EdgeReviewers holds the string denoting the reviewers edge name in mutations.
	EdgeReviewers = "reviewers"
	// Table holds the table name of the pullrequest in the database.
	Table = "pull_requests"
	// AuthorTable is the table that holds the author relation/edge.
	AuthorTable = "pull_requests"
	// AuthorInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	AuthorInverseTable = "users"
	// AuthorColumn is the table column denoting the author relation/edge.
	AuthorColumn = "author_id"
	// ReviewersTable is the table that holds the reviewers relation/edge.
	ReviewersTable = "users"
	// ReviewersInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	ReviewersInverseTable = "users"
	// ReviewersColumn is the table column denoting the reviewers relation/edge.
	ReviewersColumn = "pull_request_reviewers"
)

// Columns holds all SQL columns for pullrequest fields.
var Columns = []string{
	FieldID,
	FieldPullRequestName,
	FieldAuthorID,
	FieldStatus,
	FieldAssignedReviewers,
	FieldCreatedAt,
	FieldMergedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "pull_requests"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_assigned_reviews",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// PullRequestNameValidator is a validator for the "pull_request_name" field. It is called by the builders before save.
	PullRequestNameValidator func(string) error
	// DefaultAssignedReviewers holds the default value on creation for the "assigned_reviewers" field.
	DefaultAssignedReviewers []uuid.UUID
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the PullRequest queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPullRequestName orders the results by the pull_request_name field.
func ByPullRequestName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPullRequestName, opts...).ToFunc()
}

// ByAuthorID orders the results by the author_id field.
func ByAuthorID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthorID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByMergedAt orders the results by the merged_at field.
func ByMergedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMergedAt, opts...).ToFunc()
}

// ByAuthorField orders the results by author field.
func ByAuthorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAuthorStep(), sql.OrderByField(field, opts...))
	}
}

// ByReviewersCount orders the results by reviewers count.
func ByReviewersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newReviewersStep(), opts...)
	}
}

// ByReviewers orders the results by reviewers terms.
func ByReviewers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReviewersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newAuthorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AuthorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AuthorTable, AuthorColumn),
	)
}
func newReviewersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReviewersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ReviewersTable, ReviewersColumn),
	)
}
