// Code generated by ent, DO NOT EDIT.

package pullrequest

import (
	"AvitoTechTask/internal/domain/types"
	"AvitoTechTask/pkg/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldLTE(FieldID, id))
}

// PullRequestName applies equality check predicate on the "pull_request_name" field. It's identical to PullRequestNameEQ.
func PullRequestName(v string) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldEQ(FieldPullRequestName, v))
}

// AuthorID applies equality check predicate on the "author_id" field. It's identical to AuthorIDEQ.
func AuthorID(v uuid.UUID) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldEQ(FieldAuthorID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v types.PullRequestStatus) predicate.PullRequest {
	vc := int(v)
	return predicate.PullRequest(sql.FieldEQ(FieldStatus, vc))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// MergedAt applies equality check predicate on the "merged_at" field. It's identical to MergedAtEQ.
func MergedAt(v time.Time) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldEQ(FieldMergedAt, v))
}

// PullRequestNameEQ applies the EQ predicate on the "pull_request_name" field.
func PullRequestNameEQ(v string) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldEQ(FieldPullRequestName, v))
}

// PullRequestNameNEQ applies the NEQ predicate on the "pull_request_name" field.
func PullRequestNameNEQ(v string) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldNEQ(FieldPullRequestName, v))
}

// PullRequestNameIn applies the In predicate on the "pull_request_name" field.
func PullRequestNameIn(vs ...string) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldIn(FieldPullRequestName, vs...))
}

// PullRequestNameNotIn applies the NotIn predicate on the "pull_request_name" field.
func PullRequestNameNotIn(vs ...string) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldNotIn(FieldPullRequestName, vs...))
}

// PullRequestNameGT applies the GT predicate on the "pull_request_name" field.
func PullRequestNameGT(v string) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldGT(FieldPullRequestName, v))
}

// PullRequestNameGTE applies the GTE predicate on the "pull_request_name" field.
func PullRequestNameGTE(v string) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldGTE(FieldPullRequestName, v))
}

// PullRequestNameLT applies the LT predicate on the "pull_request_name" field.
func PullRequestNameLT(v string) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldLT(FieldPullRequestName, v))
}

// PullRequestNameLTE applies the LTE predicate on the "pull_request_name" field.
func PullRequestNameLTE(v string) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldLTE(FieldPullRequestName, v))
}

// PullRequestNameContains applies the Contains predicate on the "pull_request_name" field.
func PullRequestNameContains(v string) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldContains(FieldPullRequestName, v))
}

// PullRequestNameHasPrefix applies the HasPrefix predicate on the "pull_request_name" field.
func PullRequestNameHasPrefix(v string) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldHasPrefix(FieldPullRequestName, v))
}

// PullRequestNameHasSuffix applies the HasSuffix predicate on the "pull_request_name" field.
func PullRequestNameHasSuffix(v string) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldHasSuffix(FieldPullRequestName, v))
}

// PullRequestNameEqualFold applies the EqualFold predicate on the "pull_request_name" field.
func PullRequestNameEqualFold(v string) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldEqualFold(FieldPullRequestName, v))
}

// PullRequestNameContainsFold applies the ContainsFold predicate on the "pull_request_name" field.
func PullRequestNameContainsFold(v string) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldContainsFold(FieldPullRequestName, v))
}

// AuthorIDEQ applies the EQ predicate on the "author_id" field.
func AuthorIDEQ(v uuid.UUID) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldEQ(FieldAuthorID, v))
}

// AuthorIDNEQ applies the NEQ predicate on the "author_id" field.
func AuthorIDNEQ(v uuid.UUID) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldNEQ(FieldAuthorID, v))
}

// AuthorIDIn applies the In predicate on the "author_id" field.
func AuthorIDIn(vs ...uuid.UUID) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldIn(FieldAuthorID, vs...))
}

// AuthorIDNotIn applies the NotIn predicate on the "author_id" field.
func AuthorIDNotIn(vs ...uuid.UUID) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldNotIn(FieldAuthorID, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v types.PullRequestStatus) predicate.PullRequest {
	vc := int(v)
	return predicate.PullRequest(sql.FieldEQ(FieldStatus, vc))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v types.PullRequestStatus) predicate.PullRequest {
	vc := int(v)
	return predicate.PullRequest(sql.FieldNEQ(FieldStatus, vc))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...types.PullRequestStatus) predicate.PullRequest {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int(vs[i])
	}
	return predicate.PullRequest(sql.FieldIn(FieldStatus, v...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...types.PullRequestStatus) predicate.PullRequest {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int(vs[i])
	}
	return predicate.PullRequest(sql.FieldNotIn(FieldStatus, v...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v types.PullRequestStatus) predicate.PullRequest {
	vc := int(v)
	return predicate.PullRequest(sql.FieldGT(FieldStatus, vc))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v types.PullRequestStatus) predicate.PullRequest {
	vc := int(v)
	return predicate.PullRequest(sql.FieldGTE(FieldStatus, vc))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v types.PullRequestStatus) predicate.PullRequest {
	vc := int(v)
	return predicate.PullRequest(sql.FieldLT(FieldStatus, vc))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v types.PullRequestStatus) predicate.PullRequest {
	vc := int(v)
	return predicate.PullRequest(sql.FieldLTE(FieldStatus, vc))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldLTE(FieldCreatedAt, v))
}

// MergedAtEQ applies the EQ predicate on the "merged_at" field.
func MergedAtEQ(v time.Time) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldEQ(FieldMergedAt, v))
}

// MergedAtNEQ applies the NEQ predicate on the "merged_at" field.
func MergedAtNEQ(v time.Time) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldNEQ(FieldMergedAt, v))
}

// MergedAtIn applies the In predicate on the "merged_at" field.
func MergedAtIn(vs ...time.Time) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldIn(FieldMergedAt, vs...))
}

// MergedAtNotIn applies the NotIn predicate on the "merged_at" field.
func MergedAtNotIn(vs ...time.Time) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldNotIn(FieldMergedAt, vs...))
}

// MergedAtGT applies the GT predicate on the "merged_at" field.
func MergedAtGT(v time.Time) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldGT(FieldMergedAt, v))
}

// MergedAtGTE applies the GTE predicate on the "merged_at" field.
func MergedAtGTE(v time.Time) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldGTE(FieldMergedAt, v))
}

// MergedAtLT applies the LT predicate on the "merged_at" field.
func MergedAtLT(v time.Time) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldLT(FieldMergedAt, v))
}

// MergedAtLTE applies the LTE predicate on the "merged_at" field.
func MergedAtLTE(v time.Time) predicate.PullRequest {
	return predicate.PullRequest(sql.FieldLTE(FieldMergedAt, v))
}

// MergedAtIsNil applies the IsNil predicate on the "merged_at" field.
func MergedAtIsNil() predicate.PullRequest {
	return predicate.PullRequest(sql.FieldIsNull(FieldMergedAt))
}

// MergedAtNotNil applies the NotNil predicate on the "merged_at" field.
func MergedAtNotNil() predicate.PullRequest {
	return predicate.PullRequest(sql.FieldNotNull(FieldMergedAt))
}

// HasAuthor applies the HasEdge predicate on the "author" edge.
func HasAuthor() predicate.PullRequest {
	return predicate.PullRequest(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AuthorTable, AuthorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAuthorWith applies the HasEdge predicate on the "author" edge with a given conditions (other predicates).
func HasAuthorWith(preds ...predicate.User) predicate.PullRequest {
	return predicate.PullRequest(func(s *sql.Selector) {
		step := newAuthorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasReviewers applies the HasEdge predicate on the "reviewers" edge.
func HasReviewers() predicate.PullRequest {
	return predicate.PullRequest(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ReviewersTable, ReviewersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReviewersWith applies the HasEdge predicate on the "reviewers" edge with a given conditions (other predicates).
func HasReviewersWith(preds ...predicate.User) predicate.PullRequest {
	return predicate.PullRequest(func(s *sql.Selector) {
		step := newReviewersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PullRequest) predicate.PullRequest {
	return predicate.PullRequest(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PullRequest) predicate.PullRequest {
	return predicate.PullRequest(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PullRequest) predicate.PullRequest {
	return predicate.PullRequest(sql.NotPredicates(p))
}
