// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PullRequestsColumns holds the columns for the "pull_requests" table.
	PullRequestsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "pull_request_name", Type: field.TypeString, Unique: true},
		{Name: "status", Type: field.TypeInt},
		{Name: "assigned_reviewers", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "merged_at", Type: field.TypeTime, Nullable: true},
		{Name: "author_id", Type: field.TypeUUID},
		{Name: "user_assigned_reviews", Type: field.TypeUUID, Nullable: true},
	}
	// PullRequestsTable holds the schema information for the "pull_requests" table.
	PullRequestsTable = &schema.Table{
		Name:       "pull_requests",
		Columns:    PullRequestsColumns,
		PrimaryKey: []*schema.Column{PullRequestsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "pull_requests_users_authored_pull_requests",
				Columns:    []*schema.Column{PullRequestsColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "pull_requests_users_assigned_reviews",
				Columns:    []*schema.Column{PullRequestsColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "pullrequest_author_id",
				Unique:  false,
				Columns: []*schema.Column{PullRequestsColumns[6]},
			},
			{
				Name:    "pullrequest_status",
				Unique:  false,
				Columns: []*schema.Column{PullRequestsColumns[2]},
			},
			{
				Name:    "pullrequest_created_at",
				Unique:  false,
				Columns: []*schema.Column{PullRequestsColumns[4]},
			},
		},
	}
	// TeamsColumns holds the columns for the "teams" table.
	TeamsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "team_name", Type: field.TypeString, Unique: true},
	}
	// TeamsTable holds the schema information for the "teams" table.
	TeamsTable = &schema.Table{
		Name:       "teams",
		Columns:    TeamsColumns,
		PrimaryKey: []*schema.Column{TeamsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "team_team_name",
				Unique:  false,
				Columns: []*schema.Column{TeamsColumns[1]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "pull_request_reviewers", Type: field.TypeUUID, Nullable: true},
		{Name: "team_members", Type: field.TypeUUID, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "users_pull_requests_reviewers",
				Columns:    []*schema.Column{UsersColumns[3]},
				RefColumns: []*schema.Column{PullRequestsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "users_teams_members",
				Columns:    []*schema.Column{UsersColumns[4]},
				RefColumns: []*schema.Column{TeamsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "user_username",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[1]},
			},
			{
				Name:    "user_is_active",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PullRequestsTable,
		TeamsTable,
		UsersTable,
	}
)

func init() {
	PullRequestsTable.ForeignKeys[0].RefTable = UsersTable
	PullRequestsTable.ForeignKeys[1].RefTable = UsersTable
	UsersTable.ForeignKeys[0].RefTable = PullRequestsTable
	UsersTable.ForeignKeys[1].RefTable = TeamsTable
}
