// Code generated by ent, DO NOT EDIT.

package user

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// EdgeAuthoredPullRequests holds the string denoting the authored_pull_requests edge name in mutations.
	EdgeAuthoredPullRequests = "authored_pull_requests"
	// EdgeAssignedReviews holds the string denoting the assigned_reviews edge name in mutations.
	EdgeAssignedReviews = "assigned_reviews"
	// EdgeTeam holds the string denoting the team edge name in mutations.
	EdgeTeam = "team"
	// Table holds the table name of the user in the database.
	Table = "users"
	// AuthoredPullRequestsTable is the table that holds the authored_pull_requests relation/edge.
	AuthoredPullRequestsTable = "pull_requests"
	// AuthoredPullRequestsInverseTable is the table name for the PullRequest entity.
	// It exists in this package in order to avoid circular dependency with the "pullrequest" package.
	AuthoredPullRequestsInverseTable = "pull_requests"
	// AuthoredPullRequestsColumn is the table column denoting the authored_pull_requests relation/edge.
	AuthoredPullRequestsColumn = "author_id"
	// AssignedReviewsTable is the table that holds the assigned_reviews relation/edge.
	AssignedReviewsTable = "pull_requests"
	// AssignedReviewsInverseTable is the table name for the PullRequest entity.
	// It exists in this package in order to avoid circular dependency with the "pullrequest" package.
	AssignedReviewsInverseTable = "pull_requests"
	// AssignedReviewsColumn is the table column denoting the assigned_reviews relation/edge.
	AssignedReviewsColumn = "user_assigned_reviews"
	// TeamTable is the table that holds the team relation/edge.
	TeamTable = "users"
	// TeamInverseTable is the table name for the Team entity.
	// It exists in this package in order to avoid circular dependency with the "team" package.
	TeamInverseTable = "teams"
	// TeamColumn is the table column denoting the team relation/edge.
	TeamColumn = "team_members"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUsername,
	FieldIsActive,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "users"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"pull_request_reviewers",
	"team_members",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	UsernameValidator func(string) error
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}

// ByAuthoredPullRequestsCount orders the results by authored_pull_requests count.
func ByAuthoredPullRequestsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAuthoredPullRequestsStep(), opts...)
	}
}

// ByAuthoredPullRequests orders the results by authored_pull_requests terms.
func ByAuthoredPullRequests(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAuthoredPullRequestsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAssignedReviewsCount orders the results by assigned_reviews count.
func ByAssignedReviewsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAssignedReviewsStep(), opts...)
	}
}

// ByAssignedReviews orders the results by assigned_reviews terms.
func ByAssignedReviews(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAssignedReviewsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTeamField orders the results by team field.
func ByTeamField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTeamStep(), sql.OrderByField(field, opts...))
	}
}
func newAuthoredPullRequestsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AuthoredPullRequestsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AuthoredPullRequestsTable, AuthoredPullRequestsColumn),
	)
}
func newAssignedReviewsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AssignedReviewsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AssignedReviewsTable, AssignedReviewsColumn),
	)
}
func newTeamStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TeamInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TeamTable, TeamColumn),
	)
}
