// Code generated by ent, DO NOT EDIT.

package ent

import (
	"AvitoTechTask/pkg/ent/predicate"
	"AvitoTechTask/pkg/ent/pullrequest"
	"AvitoTechTask/pkg/ent/team"
	"AvitoTechTask/pkg/ent/user"
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypePullRequest = "PullRequest"
	TypeTeam        = "Team"
	TypeUser        = "User"
)

// PullRequestMutation represents an operation that mutates the PullRequest nodes in the graph.
type PullRequestMutation struct {
	config
	op                       Op
	typ                      string
	id                       *uuid.UUID
	pull_request_name        *string
	status                   *pullrequest.Status
	assigned_reviewers       *[]uuid.UUID
	appendassigned_reviewers []uuid.UUID
	created_at               *time.Time
	merged_at                *time.Time
	clearedFields            map[string]struct{}
	author                   *uuid.UUID
	clearedauthor            bool
	reviewers                map[uuid.UUID]struct{}
	removedreviewers         map[uuid.UUID]struct{}
	clearedreviewers         bool
	done                     bool
	oldValue                 func(context.Context) (*PullRequest, error)
	predicates               []predicate.PullRequest
}

var _ ent.Mutation = (*PullRequestMutation)(nil)

// pullrequestOption allows management of the mutation configuration using functional options.
type pullrequestOption func(*PullRequestMutation)

// newPullRequestMutation creates new mutation for the PullRequest entity.
func newPullRequestMutation(c config, op Op, opts ...pullrequestOption) *PullRequestMutation {
	m := &PullRequestMutation{
		config:        c,
		op:            op,
		typ:           TypePullRequest,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withPullRequestID sets the ID field of the mutation.
func withPullRequestID(id uuid.UUID) pullrequestOption {
	return func(m *PullRequestMutation) {
		var (
			err   error
			once  sync.Once
			value *PullRequest
		)
		m.oldValue = func(ctx context.Context) (*PullRequest, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().PullRequest.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withPullRequest sets the old PullRequest of the mutation.
func withPullRequest(node *PullRequest) pullrequestOption {
	return func(m *PullRequestMutation) {
		m.oldValue = func(context.Context) (*PullRequest, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m PullRequestMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m PullRequestMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of PullRequest entities.
func (m *PullRequestMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *PullRequestMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *PullRequestMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().PullRequest.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetPullRequestName sets the "pull_request_name" field.
func (m *PullRequestMutation) SetPullRequestName(s string) {
	m.pull_request_name = &s
}

// PullRequestName returns the value of the "pull_request_name" field in the mutation.
func (m *PullRequestMutation) PullRequestName() (r string, exists bool) {
	v := m.pull_request_name
	if v == nil {
		return
	}
	return *v, true
}

// OldPullRequestName returns the old "pull_request_name" field's value of the PullRequest entity.
// If the PullRequest object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PullRequestMutation) OldPullRequestName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPullRequestName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPullRequestName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPullRequestName: %w", err)
	}
	return oldValue.PullRequestName, nil
}

// ResetPullRequestName resets all changes to the "pull_request_name" field.
func (m *PullRequestMutation) ResetPullRequestName() {
	m.pull_request_name = nil
}

// SetAuthorID sets the "author_id" field.
func (m *PullRequestMutation) SetAuthorID(u uuid.UUID) {
	m.author = &u
}

// AuthorID returns the value of the "author_id" field in the mutation.
func (m *PullRequestMutation) AuthorID() (r uuid.UUID, exists bool) {
	v := m.author
	if v == nil {
		return
	}
	return *v, true
}

// OldAuthorID returns the old "author_id" field's value of the PullRequest entity.
// If the PullRequest object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PullRequestMutation) OldAuthorID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAuthorID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAuthorID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAuthorID: %w", err)
	}
	return oldValue.AuthorID, nil
}

// ResetAuthorID resets all changes to the "author_id" field.
func (m *PullRequestMutation) ResetAuthorID() {
	m.author = nil
}

// SetStatus sets the "status" field.
func (m *PullRequestMutation) SetStatus(pu pullrequest.Status) {
	m.status = &pu
}

// Status returns the value of the "status" field in the mutation.
func (m *PullRequestMutation) Status() (r pullrequest.Status, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the PullRequest entity.
// If the PullRequest object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PullRequestMutation) OldStatus(ctx context.Context) (v pullrequest.Status, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *PullRequestMutation) ResetStatus() {
	m.status = nil
}

// SetAssignedReviewers sets the "assigned_reviewers" field.
func (m *PullRequestMutation) SetAssignedReviewers(u []uuid.UUID) {
	m.assigned_reviewers = &u
	m.appendassigned_reviewers = nil
}

// AssignedReviewers returns the value of the "assigned_reviewers" field in the mutation.
func (m *PullRequestMutation) AssignedReviewers() (r []uuid.UUID, exists bool) {
	v := m.assigned_reviewers
	if v == nil {
		return
	}
	return *v, true
}

// OldAssignedReviewers returns the old "assigned_reviewers" field's value of the PullRequest entity.
// If the PullRequest object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PullRequestMutation) OldAssignedReviewers(ctx context.Context) (v []uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAssignedReviewers is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAssignedReviewers requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAssignedReviewers: %w", err)
	}
	return oldValue.AssignedReviewers, nil
}

// AppendAssignedReviewers adds u to the "assigned_reviewers" field.
func (m *PullRequestMutation) AppendAssignedReviewers(u []uuid.UUID) {
	m.appendassigned_reviewers = append(m.appendassigned_reviewers, u...)
}

// AppendedAssignedReviewers returns the list of values that were appended to the "assigned_reviewers" field in this mutation.
func (m *PullRequestMutation) AppendedAssignedReviewers() ([]uuid.UUID, bool) {
	if len(m.appendassigned_reviewers) == 0 {
		return nil, false
	}
	return m.appendassigned_reviewers, true
}

// ResetAssignedReviewers resets all changes to the "assigned_reviewers" field.
func (m *PullRequestMutation) ResetAssignedReviewers() {
	m.assigned_reviewers = nil
	m.appendassigned_reviewers = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *PullRequestMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *PullRequestMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the PullRequest entity.
// If the PullRequest object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PullRequestMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *PullRequestMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetMergedAt sets the "merged_at" field.
func (m *PullRequestMutation) SetMergedAt(t time.Time) {
	m.merged_at = &t
}

// MergedAt returns the value of the "merged_at" field in the mutation.
func (m *PullRequestMutation) MergedAt() (r time.Time, exists bool) {
	v := m.merged_at
	if v == nil {
		return
	}
	return *v, true
}

// OldMergedAt returns the old "merged_at" field's value of the PullRequest entity.
// If the PullRequest object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PullRequestMutation) OldMergedAt(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMergedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMergedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMergedAt: %w", err)
	}
	return oldValue.MergedAt, nil
}

// ClearMergedAt clears the value of the "merged_at" field.
func (m *PullRequestMutation) ClearMergedAt() {
	m.merged_at = nil
	m.clearedFields[pullrequest.FieldMergedAt] = struct{}{}
}

// MergedAtCleared returns if the "merged_at" field was cleared in this mutation.
func (m *PullRequestMutation) MergedAtCleared() bool {
	_, ok := m.clearedFields[pullrequest.FieldMergedAt]
	return ok
}

// ResetMergedAt resets all changes to the "merged_at" field.
func (m *PullRequestMutation) ResetMergedAt() {
	m.merged_at = nil
	delete(m.clearedFields, pullrequest.FieldMergedAt)
}

// ClearAuthor clears the "author" edge to the User entity.
func (m *PullRequestMutation) ClearAuthor() {
	m.clearedauthor = true
	m.clearedFields[pullrequest.FieldAuthorID] = struct{}{}
}

// AuthorCleared reports if the "author" edge to the User entity was cleared.
func (m *PullRequestMutation) AuthorCleared() bool {
	return m.clearedauthor
}

// AuthorIDs returns the "author" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// AuthorID instead. It exists only for internal usage by the builders.
func (m *PullRequestMutation) AuthorIDs() (ids []uuid.UUID) {
	if id := m.author; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetAuthor resets all changes to the "author" edge.
func (m *PullRequestMutation) ResetAuthor() {
	m.author = nil
	m.clearedauthor = false
}

// AddReviewerIDs adds the "reviewers" edge to the User entity by ids.
func (m *PullRequestMutation) AddReviewerIDs(ids ...uuid.UUID) {
	if m.reviewers == nil {
		m.reviewers = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		m.reviewers[ids[i]] = struct{}{}
	}
}

// ClearReviewers clears the "reviewers" edge to the User entity.
func (m *PullRequestMutation) ClearReviewers() {
	m.clearedreviewers = true
}

// ReviewersCleared reports if the "reviewers" edge to the User entity was cleared.
func (m *PullRequestMutation) ReviewersCleared() bool {
	return m.clearedreviewers
}

// RemoveReviewerIDs removes the "reviewers" edge to the User entity by IDs.
func (m *PullRequestMutation) RemoveReviewerIDs(ids ...uuid.UUID) {
	if m.removedreviewers == nil {
		m.removedreviewers = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		delete(m.reviewers, ids[i])
		m.removedreviewers[ids[i]] = struct{}{}
	}
}

// RemovedReviewers returns the removed IDs of the "reviewers" edge to the User entity.
func (m *PullRequestMutation) RemovedReviewersIDs() (ids []uuid.UUID) {
	for id := range m.removedreviewers {
		ids = append(ids, id)
	}
	return
}

// ReviewersIDs returns the "reviewers" edge IDs in the mutation.
func (m *PullRequestMutation) ReviewersIDs() (ids []uuid.UUID) {
	for id := range m.reviewers {
		ids = append(ids, id)
	}
	return
}

// ResetReviewers resets all changes to the "reviewers" edge.
func (m *PullRequestMutation) ResetReviewers() {
	m.reviewers = nil
	m.clearedreviewers = false
	m.removedreviewers = nil
}

// Where appends a list predicates to the PullRequestMutation builder.
func (m *PullRequestMutation) Where(ps ...predicate.PullRequest) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the PullRequestMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *PullRequestMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.PullRequest, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *PullRequestMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *PullRequestMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (PullRequest).
func (m *PullRequestMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *PullRequestMutation) Fields() []string {
	fields := make([]string, 0, 6)
	if m.pull_request_name != nil {
		fields = append(fields, pullrequest.FieldPullRequestName)
	}
	if m.author != nil {
		fields = append(fields, pullrequest.FieldAuthorID)
	}
	if m.status != nil {
		fields = append(fields, pullrequest.FieldStatus)
	}
	if m.assigned_reviewers != nil {
		fields = append(fields, pullrequest.FieldAssignedReviewers)
	}
	if m.created_at != nil {
		fields = append(fields, pullrequest.FieldCreatedAt)
	}
	if m.merged_at != nil {
		fields = append(fields, pullrequest.FieldMergedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *PullRequestMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case pullrequest.FieldPullRequestName:
		return m.PullRequestName()
	case pullrequest.FieldAuthorID:
		return m.AuthorID()
	case pullrequest.FieldStatus:
		return m.Status()
	case pullrequest.FieldAssignedReviewers:
		return m.AssignedReviewers()
	case pullrequest.FieldCreatedAt:
		return m.CreatedAt()
	case pullrequest.FieldMergedAt:
		return m.MergedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *PullRequestMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case pullrequest.FieldPullRequestName:
		return m.OldPullRequestName(ctx)
	case pullrequest.FieldAuthorID:
		return m.OldAuthorID(ctx)
	case pullrequest.FieldStatus:
		return m.OldStatus(ctx)
	case pullrequest.FieldAssignedReviewers:
		return m.OldAssignedReviewers(ctx)
	case pullrequest.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case pullrequest.FieldMergedAt:
		return m.OldMergedAt(ctx)
	}
	return nil, fmt.Errorf("unknown PullRequest field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PullRequestMutation) SetField(name string, value ent.Value) error {
	switch name {
	case pullrequest.FieldPullRequestName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPullRequestName(v)
		return nil
	case pullrequest.FieldAuthorID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAuthorID(v)
		return nil
	case pullrequest.FieldStatus:
		v, ok := value.(pullrequest.Status)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case pullrequest.FieldAssignedReviewers:
		v, ok := value.([]uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAssignedReviewers(v)
		return nil
	case pullrequest.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case pullrequest.FieldMergedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMergedAt(v)
		return nil
	}
	return fmt.Errorf("unknown PullRequest field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *PullRequestMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *PullRequestMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PullRequestMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown PullRequest numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *PullRequestMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(pullrequest.FieldMergedAt) {
		fields = append(fields, pullrequest.FieldMergedAt)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *PullRequestMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *PullRequestMutation) ClearField(name string) error {
	switch name {
	case pullrequest.FieldMergedAt:
		m.ClearMergedAt()
		return nil
	}
	return fmt.Errorf("unknown PullRequest nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *PullRequestMutation) ResetField(name string) error {
	switch name {
	case pullrequest.FieldPullRequestName:
		m.ResetPullRequestName()
		return nil
	case pullrequest.FieldAuthorID:
		m.ResetAuthorID()
		return nil
	case pullrequest.FieldStatus:
		m.ResetStatus()
		return nil
	case pullrequest.FieldAssignedReviewers:
		m.ResetAssignedReviewers()
		return nil
	case pullrequest.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case pullrequest.FieldMergedAt:
		m.ResetMergedAt()
		return nil
	}
	return fmt.Errorf("unknown PullRequest field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *PullRequestMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.author != nil {
		edges = append(edges, pullrequest.EdgeAuthor)
	}
	if m.reviewers != nil {
		edges = append(edges, pullrequest.EdgeReviewers)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *PullRequestMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case pullrequest.EdgeAuthor:
		if id := m.author; id != nil {
			return []ent.Value{*id}
		}
	case pullrequest.EdgeReviewers:
		ids := make([]ent.Value, 0, len(m.reviewers))
		for id := range m.reviewers {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *PullRequestMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	if m.removedreviewers != nil {
		edges = append(edges, pullrequest.EdgeReviewers)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *PullRequestMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case pullrequest.EdgeReviewers:
		ids := make([]ent.Value, 0, len(m.removedreviewers))
		for id := range m.removedreviewers {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *PullRequestMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedauthor {
		edges = append(edges, pullrequest.EdgeAuthor)
	}
	if m.clearedreviewers {
		edges = append(edges, pullrequest.EdgeReviewers)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *PullRequestMutation) EdgeCleared(name string) bool {
	switch name {
	case pullrequest.EdgeAuthor:
		return m.clearedauthor
	case pullrequest.EdgeReviewers:
		return m.clearedreviewers
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *PullRequestMutation) ClearEdge(name string) error {
	switch name {
	case pullrequest.EdgeAuthor:
		m.ClearAuthor()
		return nil
	}
	return fmt.Errorf("unknown PullRequest unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *PullRequestMutation) ResetEdge(name string) error {
	switch name {
	case pullrequest.EdgeAuthor:
		m.ResetAuthor()
		return nil
	case pullrequest.EdgeReviewers:
		m.ResetReviewers()
		return nil
	}
	return fmt.Errorf("unknown PullRequest edge %s", name)
}

// TeamMutation represents an operation that mutates the Team nodes in the graph.
type TeamMutation struct {
	config
	op             Op
	typ            string
	id             *uuid.UUID
	team_name      *string
	clearedFields  map[string]struct{}
	members        map[uuid.UUID]struct{}
	removedmembers map[uuid.UUID]struct{}
	clearedmembers bool
	done           bool
	oldValue       func(context.Context) (*Team, error)
	predicates     []predicate.Team
}

var _ ent.Mutation = (*TeamMutation)(nil)

// teamOption allows management of the mutation configuration using functional options.
type teamOption func(*TeamMutation)

// newTeamMutation creates new mutation for the Team entity.
func newTeamMutation(c config, op Op, opts ...teamOption) *TeamMutation {
	m := &TeamMutation{
		config:        c,
		op:            op,
		typ:           TypeTeam,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withTeamID sets the ID field of the mutation.
func withTeamID(id uuid.UUID) teamOption {
	return func(m *TeamMutation) {
		var (
			err   error
			once  sync.Once
			value *Team
		)
		m.oldValue = func(ctx context.Context) (*Team, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Team.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withTeam sets the old Team of the mutation.
func withTeam(node *Team) teamOption {
	return func(m *TeamMutation) {
		m.oldValue = func(context.Context) (*Team, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m TeamMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m TeamMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Team entities.
func (m *TeamMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *TeamMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *TeamMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Team.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetTeamName sets the "team_name" field.
func (m *TeamMutation) SetTeamName(s string) {
	m.team_name = &s
}

// TeamName returns the value of the "team_name" field in the mutation.
func (m *TeamMutation) TeamName() (r string, exists bool) {
	v := m.team_name
	if v == nil {
		return
	}
	return *v, true
}

// OldTeamName returns the old "team_name" field's value of the Team entity.
// If the Team object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TeamMutation) OldTeamName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTeamName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTeamName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTeamName: %w", err)
	}
	return oldValue.TeamName, nil
}

// ResetTeamName resets all changes to the "team_name" field.
func (m *TeamMutation) ResetTeamName() {
	m.team_name = nil
}

// AddMemberIDs adds the "members" edge to the User entity by ids.
func (m *TeamMutation) AddMemberIDs(ids ...uuid.UUID) {
	if m.members == nil {
		m.members = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		m.members[ids[i]] = struct{}{}
	}
}

// ClearMembers clears the "members" edge to the User entity.
func (m *TeamMutation) ClearMembers() {
	m.clearedmembers = true
}

// MembersCleared reports if the "members" edge to the User entity was cleared.
func (m *TeamMutation) MembersCleared() bool {
	return m.clearedmembers
}

// RemoveMemberIDs removes the "members" edge to the User entity by IDs.
func (m *TeamMutation) RemoveMemberIDs(ids ...uuid.UUID) {
	if m.removedmembers == nil {
		m.removedmembers = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		delete(m.members, ids[i])
		m.removedmembers[ids[i]] = struct{}{}
	}
}

// RemovedMembers returns the removed IDs of the "members" edge to the User entity.
func (m *TeamMutation) RemovedMembersIDs() (ids []uuid.UUID) {
	for id := range m.removedmembers {
		ids = append(ids, id)
	}
	return
}

// MembersIDs returns the "members" edge IDs in the mutation.
func (m *TeamMutation) MembersIDs() (ids []uuid.UUID) {
	for id := range m.members {
		ids = append(ids, id)
	}
	return
}

// ResetMembers resets all changes to the "members" edge.
func (m *TeamMutation) ResetMembers() {
	m.members = nil
	m.clearedmembers = false
	m.removedmembers = nil
}

// Where appends a list predicates to the TeamMutation builder.
func (m *TeamMutation) Where(ps ...predicate.Team) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the TeamMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *TeamMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Team, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *TeamMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *TeamMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Team).
func (m *TeamMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *TeamMutation) Fields() []string {
	fields := make([]string, 0, 1)
	if m.team_name != nil {
		fields = append(fields, team.FieldTeamName)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *TeamMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case team.FieldTeamName:
		return m.TeamName()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *TeamMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case team.FieldTeamName:
		return m.OldTeamName(ctx)
	}
	return nil, fmt.Errorf("unknown Team field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TeamMutation) SetField(name string, value ent.Value) error {
	switch name {
	case team.FieldTeamName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTeamName(v)
		return nil
	}
	return fmt.Errorf("unknown Team field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *TeamMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *TeamMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TeamMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Team numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *TeamMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *TeamMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *TeamMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Team nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *TeamMutation) ResetField(name string) error {
	switch name {
	case team.FieldTeamName:
		m.ResetTeamName()
		return nil
	}
	return fmt.Errorf("unknown Team field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *TeamMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.members != nil {
		edges = append(edges, team.EdgeMembers)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *TeamMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case team.EdgeMembers:
		ids := make([]ent.Value, 0, len(m.members))
		for id := range m.members {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *TeamMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedmembers != nil {
		edges = append(edges, team.EdgeMembers)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *TeamMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case team.EdgeMembers:
		ids := make([]ent.Value, 0, len(m.removedmembers))
		for id := range m.removedmembers {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *TeamMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedmembers {
		edges = append(edges, team.EdgeMembers)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *TeamMutation) EdgeCleared(name string) bool {
	switch name {
	case team.EdgeMembers:
		return m.clearedmembers
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *TeamMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Team unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *TeamMutation) ResetEdge(name string) error {
	switch name {
	case team.EdgeMembers:
		m.ResetMembers()
		return nil
	}
	return fmt.Errorf("unknown Team edge %s", name)
}

// UserMutation represents an operation that mutates the User nodes in the graph.
type UserMutation struct {
	config
	op                            Op
	typ                           string
	id                            *uuid.UUID
	username                      *string
	is_active                     *bool
	clearedFields                 map[string]struct{}
	authored_pull_requests        map[uuid.UUID]struct{}
	removedauthored_pull_requests map[uuid.UUID]struct{}
	clearedauthored_pull_requests bool
	assigned_reviews              map[uuid.UUID]struct{}
	removedassigned_reviews       map[uuid.UUID]struct{}
	clearedassigned_reviews       bool
	team                          *uuid.UUID
	clearedteam                   bool
	done                          bool
	oldValue                      func(context.Context) (*User, error)
	predicates                    []predicate.User
}

var _ ent.Mutation = (*UserMutation)(nil)

// userOption allows management of the mutation configuration using functional options.
type userOption func(*UserMutation)

// newUserMutation creates new mutation for the User entity.
func newUserMutation(c config, op Op, opts ...userOption) *UserMutation {
	m := &UserMutation{
		config:        c,
		op:            op,
		typ:           TypeUser,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withUserID sets the ID field of the mutation.
func withUserID(id uuid.UUID) userOption {
	return func(m *UserMutation) {
		var (
			err   error
			once  sync.Once
			value *User
		)
		m.oldValue = func(ctx context.Context) (*User, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().User.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withUser sets the old User of the mutation.
func withUser(node *User) userOption {
	return func(m *UserMutation) {
		m.oldValue = func(context.Context) (*User, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m UserMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m UserMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of User entities.
func (m *UserMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *UserMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *UserMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().User.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetUsername sets the "username" field.
func (m *UserMutation) SetUsername(s string) {
	m.username = &s
}

// Username returns the value of the "username" field in the mutation.
func (m *UserMutation) Username() (r string, exists bool) {
	v := m.username
	if v == nil {
		return
	}
	return *v, true
}

// OldUsername returns the old "username" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldUsername(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUsername is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUsername requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUsername: %w", err)
	}
	return oldValue.Username, nil
}

// ResetUsername resets all changes to the "username" field.
func (m *UserMutation) ResetUsername() {
	m.username = nil
}

// SetIsActive sets the "is_active" field.
func (m *UserMutation) SetIsActive(b bool) {
	m.is_active = &b
}

// IsActive returns the value of the "is_active" field in the mutation.
func (m *UserMutation) IsActive() (r bool, exists bool) {
	v := m.is_active
	if v == nil {
		return
	}
	return *v, true
}

// OldIsActive returns the old "is_active" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldIsActive(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIsActive is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIsActive requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIsActive: %w", err)
	}
	return oldValue.IsActive, nil
}

// ResetIsActive resets all changes to the "is_active" field.
func (m *UserMutation) ResetIsActive() {
	m.is_active = nil
}

// AddAuthoredPullRequestIDs adds the "authored_pull_requests" edge to the PullRequest entity by ids.
func (m *UserMutation) AddAuthoredPullRequestIDs(ids ...uuid.UUID) {
	if m.authored_pull_requests == nil {
		m.authored_pull_requests = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		m.authored_pull_requests[ids[i]] = struct{}{}
	}
}

// ClearAuthoredPullRequests clears the "authored_pull_requests" edge to the PullRequest entity.
func (m *UserMutation) ClearAuthoredPullRequests() {
	m.clearedauthored_pull_requests = true
}

// AuthoredPullRequestsCleared reports if the "authored_pull_requests" edge to the PullRequest entity was cleared.
func (m *UserMutation) AuthoredPullRequestsCleared() bool {
	return m.clearedauthored_pull_requests
}

// RemoveAuthoredPullRequestIDs removes the "authored_pull_requests" edge to the PullRequest entity by IDs.
func (m *UserMutation) RemoveAuthoredPullRequestIDs(ids ...uuid.UUID) {
	if m.removedauthored_pull_requests == nil {
		m.removedauthored_pull_requests = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		delete(m.authored_pull_requests, ids[i])
		m.removedauthored_pull_requests[ids[i]] = struct{}{}
	}
}

// RemovedAuthoredPullRequests returns the removed IDs of the "authored_pull_requests" edge to the PullRequest entity.
func (m *UserMutation) RemovedAuthoredPullRequestsIDs() (ids []uuid.UUID) {
	for id := range m.removedauthored_pull_requests {
		ids = append(ids, id)
	}
	return
}

// AuthoredPullRequestsIDs returns the "authored_pull_requests" edge IDs in the mutation.
func (m *UserMutation) AuthoredPullRequestsIDs() (ids []uuid.UUID) {
	for id := range m.authored_pull_requests {
		ids = append(ids, id)
	}
	return
}

// ResetAuthoredPullRequests resets all changes to the "authored_pull_requests" edge.
func (m *UserMutation) ResetAuthoredPullRequests() {
	m.authored_pull_requests = nil
	m.clearedauthored_pull_requests = false
	m.removedauthored_pull_requests = nil
}

// AddAssignedReviewIDs adds the "assigned_reviews" edge to the PullRequest entity by ids.
func (m *UserMutation) AddAssignedReviewIDs(ids ...uuid.UUID) {
	if m.assigned_reviews == nil {
		m.assigned_reviews = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		m.assigned_reviews[ids[i]] = struct{}{}
	}
}

// ClearAssignedReviews clears the "assigned_reviews" edge to the PullRequest entity.
func (m *UserMutation) ClearAssignedReviews() {
	m.clearedassigned_reviews = true
}

// AssignedReviewsCleared reports if the "assigned_reviews" edge to the PullRequest entity was cleared.
func (m *UserMutation) AssignedReviewsCleared() bool {
	return m.clearedassigned_reviews
}

// RemoveAssignedReviewIDs removes the "assigned_reviews" edge to the PullRequest entity by IDs.
func (m *UserMutation) RemoveAssignedReviewIDs(ids ...uuid.UUID) {
	if m.removedassigned_reviews == nil {
		m.removedassigned_reviews = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		delete(m.assigned_reviews, ids[i])
		m.removedassigned_reviews[ids[i]] = struct{}{}
	}
}

// RemovedAssignedReviews returns the removed IDs of the "assigned_reviews" edge to the PullRequest entity.
func (m *UserMutation) RemovedAssignedReviewsIDs() (ids []uuid.UUID) {
	for id := range m.removedassigned_reviews {
		ids = append(ids, id)
	}
	return
}

// AssignedReviewsIDs returns the "assigned_reviews" edge IDs in the mutation.
func (m *UserMutation) AssignedReviewsIDs() (ids []uuid.UUID) {
	for id := range m.assigned_reviews {
		ids = append(ids, id)
	}
	return
}

// ResetAssignedReviews resets all changes to the "assigned_reviews" edge.
func (m *UserMutation) ResetAssignedReviews() {
	m.assigned_reviews = nil
	m.clearedassigned_reviews = false
	m.removedassigned_reviews = nil
}

// SetTeamID sets the "team" edge to the Team entity by id.
func (m *UserMutation) SetTeamID(id uuid.UUID) {
	m.team = &id
}

// ClearTeam clears the "team" edge to the Team entity.
func (m *UserMutation) ClearTeam() {
	m.clearedteam = true
}

// TeamCleared reports if the "team" edge to the Team entity was cleared.
func (m *UserMutation) TeamCleared() bool {
	return m.clearedteam
}

// TeamID returns the "team" edge ID in the mutation.
func (m *UserMutation) TeamID() (id uuid.UUID, exists bool) {
	if m.team != nil {
		return *m.team, true
	}
	return
}

// TeamIDs returns the "team" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// TeamID instead. It exists only for internal usage by the builders.
func (m *UserMutation) TeamIDs() (ids []uuid.UUID) {
	if id := m.team; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetTeam resets all changes to the "team" edge.
func (m *UserMutation) ResetTeam() {
	m.team = nil
	m.clearedteam = false
}

// Where appends a list predicates to the UserMutation builder.
func (m *UserMutation) Where(ps ...predicate.User) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the UserMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *UserMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.User, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *UserMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *UserMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (User).
func (m *UserMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *UserMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.username != nil {
		fields = append(fields, user.FieldUsername)
	}
	if m.is_active != nil {
		fields = append(fields, user.FieldIsActive)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *UserMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case user.FieldUsername:
		return m.Username()
	case user.FieldIsActive:
		return m.IsActive()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *UserMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case user.FieldUsername:
		return m.OldUsername(ctx)
	case user.FieldIsActive:
		return m.OldIsActive(ctx)
	}
	return nil, fmt.Errorf("unknown User field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserMutation) SetField(name string, value ent.Value) error {
	switch name {
	case user.FieldUsername:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUsername(v)
		return nil
	case user.FieldIsActive:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIsActive(v)
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *UserMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *UserMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown User numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *UserMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *UserMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *UserMutation) ClearField(name string) error {
	return fmt.Errorf("unknown User nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *UserMutation) ResetField(name string) error {
	switch name {
	case user.FieldUsername:
		m.ResetUsername()
		return nil
	case user.FieldIsActive:
		m.ResetIsActive()
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *UserMutation) AddedEdges() []string {
	edges := make([]string, 0, 3)
	if m.authored_pull_requests != nil {
		edges = append(edges, user.EdgeAuthoredPullRequests)
	}
	if m.assigned_reviews != nil {
		edges = append(edges, user.EdgeAssignedReviews)
	}
	if m.team != nil {
		edges = append(edges, user.EdgeTeam)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *UserMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case user.EdgeAuthoredPullRequests:
		ids := make([]ent.Value, 0, len(m.authored_pull_requests))
		for id := range m.authored_pull_requests {
			ids = append(ids, id)
		}
		return ids
	case user.EdgeAssignedReviews:
		ids := make([]ent.Value, 0, len(m.assigned_reviews))
		for id := range m.assigned_reviews {
			ids = append(ids, id)
		}
		return ids
	case user.EdgeTeam:
		if id := m.team; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *UserMutation) RemovedEdges() []string {
	edges := make([]string, 0, 3)
	if m.removedauthored_pull_requests != nil {
		edges = append(edges, user.EdgeAuthoredPullRequests)
	}
	if m.removedassigned_reviews != nil {
		edges = append(edges, user.EdgeAssignedReviews)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *UserMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case user.EdgeAuthoredPullRequests:
		ids := make([]ent.Value, 0, len(m.removedauthored_pull_requests))
		for id := range m.removedauthored_pull_requests {
			ids = append(ids, id)
		}
		return ids
	case user.EdgeAssignedReviews:
		ids := make([]ent.Value, 0, len(m.removedassigned_reviews))
		for id := range m.removedassigned_reviews {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *UserMutation) ClearedEdges() []string {
	edges := make([]string, 0, 3)
	if m.clearedauthored_pull_requests {
		edges = append(edges, user.EdgeAuthoredPullRequests)
	}
	if m.clearedassigned_reviews {
		edges = append(edges, user.EdgeAssignedReviews)
	}
	if m.clearedteam {
		edges = append(edges, user.EdgeTeam)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *UserMutation) EdgeCleared(name string) bool {
	switch name {
	case user.EdgeAuthoredPullRequests:
		return m.clearedauthored_pull_requests
	case user.EdgeAssignedReviews:
		return m.clearedassigned_reviews
	case user.EdgeTeam:
		return m.clearedteam
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *UserMutation) ClearEdge(name string) error {
	switch name {
	case user.EdgeTeam:
		m.ClearTeam()
		return nil
	}
	return fmt.Errorf("unknown User unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *UserMutation) ResetEdge(name string) error {
	switch name {
	case user.EdgeAuthoredPullRequests:
		m.ResetAuthoredPullRequests()
		return nil
	case user.EdgeAssignedReviews:
		m.ResetAssignedReviews()
		return nil
	case user.EdgeTeam:
		m.ResetTeam()
		return nil
	}
	return fmt.Errorf("unknown User edge %s", name)
}
