// Code generated by ent, DO NOT EDIT.

package ent

import (
	"AvitoTechTask/internal/domain/types"
	"AvitoTechTask/pkg/ent/pullrequest"
	"AvitoTechTask/pkg/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PullRequestCreate is the builder for creating a PullRequest entity.
type PullRequestCreate struct {
	config
	mutation *PullRequestMutation
	hooks    []Hook
}

// SetPullRequestName sets the "pull_request_name" field.
func (_c *PullRequestCreate) SetPullRequestName(v string) *PullRequestCreate {
	_c.mutation.SetPullRequestName(v)
	return _c
}

// SetAuthorID sets the "author_id" field.
func (_c *PullRequestCreate) SetAuthorID(v uuid.UUID) *PullRequestCreate {
	_c.mutation.SetAuthorID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *PullRequestCreate) SetStatus(v types.PullRequestStatus) *PullRequestCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetAssignedReviewers sets the "assigned_reviewers" field.
func (_c *PullRequestCreate) SetAssignedReviewers(v []uuid.UUID) *PullRequestCreate {
	_c.mutation.SetAssignedReviewers(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PullRequestCreate) SetCreatedAt(v time.Time) *PullRequestCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PullRequestCreate) SetNillableCreatedAt(v *time.Time) *PullRequestCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetMergedAt sets the "merged_at" field.
func (_c *PullRequestCreate) SetMergedAt(v time.Time) *PullRequestCreate {
	_c.mutation.SetMergedAt(v)
	return _c
}

// SetNillableMergedAt sets the "merged_at" field if the given value is not nil.
func (_c *PullRequestCreate) SetNillableMergedAt(v *time.Time) *PullRequestCreate {
	if v != nil {
		_c.SetMergedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PullRequestCreate) SetID(v uuid.UUID) *PullRequestCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PullRequestCreate) SetNillableID(v *uuid.UUID) *PullRequestCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetAuthor sets the "author" edge to the User entity.
func (_c *PullRequestCreate) SetAuthor(v *User) *PullRequestCreate {
	return _c.SetAuthorID(v.ID)
}

// AddReviewerIDs adds the "reviewers" edge to the User entity by IDs.
func (_c *PullRequestCreate) AddReviewerIDs(ids ...uuid.UUID) *PullRequestCreate {
	_c.mutation.AddReviewerIDs(ids...)
	return _c
}

// AddReviewers adds the "reviewers" edges to the User entity.
func (_c *PullRequestCreate) AddReviewers(v ...*User) *PullRequestCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddReviewerIDs(ids...)
}

// Mutation returns the PullRequestMutation object of the builder.
func (_c *PullRequestCreate) Mutation() *PullRequestMutation {
	return _c.mutation
}

// Save creates the PullRequest in the database.
func (_c *PullRequestCreate) Save(ctx context.Context) (*PullRequest, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PullRequestCreate) SaveX(ctx context.Context) *PullRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PullRequestCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PullRequestCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PullRequestCreate) defaults() {
	if _, ok := _c.mutation.AssignedReviewers(); !ok {
		v := pullrequest.DefaultAssignedReviewers
		_c.mutation.SetAssignedReviewers(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := pullrequest.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := pullrequest.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PullRequestCreate) check() error {
	if _, ok := _c.mutation.PullRequestName(); !ok {
		return &ValidationError{Name: "pull_request_name", err: errors.New(`ent: missing required field "PullRequest.pull_request_name"`)}
	}
	if v, ok := _c.mutation.PullRequestName(); ok {
		if err := pullrequest.PullRequestNameValidator(v); err != nil {
			return &ValidationError{Name: "pull_request_name", err: fmt.Errorf(`ent: validator failed for field "PullRequest.pull_request_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AuthorID(); !ok {
		return &ValidationError{Name: "author_id", err: errors.New(`ent: missing required field "PullRequest.author_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "PullRequest.status"`)}
	}
	if _, ok := _c.mutation.AssignedReviewers(); !ok {
		return &ValidationError{Name: "assigned_reviewers", err: errors.New(`ent: missing required field "PullRequest.assigned_reviewers"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PullRequest.created_at"`)}
	}
	if len(_c.mutation.AuthorIDs()) == 0 {
		return &ValidationError{Name: "author", err: errors.New(`ent: missing required edge "PullRequest.author"`)}
	}
	return nil
}

func (_c *PullRequestCreate) sqlSave(ctx context.Context) (*PullRequest, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PullRequestCreate) createSpec() (*PullRequest, *sqlgraph.CreateSpec) {
	var (
		_node = &PullRequest{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pullrequest.Table, sqlgraph.NewFieldSpec(pullrequest.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.PullRequestName(); ok {
		_spec.SetField(pullrequest.FieldPullRequestName, field.TypeString, value)
		_node.PullRequestName = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(pullrequest.FieldStatus, field.TypeInt, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.AssignedReviewers(); ok {
		_spec.SetField(pullrequest.FieldAssignedReviewers, field.TypeJSON, value)
		_node.AssignedReviewers = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(pullrequest.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.MergedAt(); ok {
		_spec.SetField(pullrequest.FieldMergedAt, field.TypeTime, value)
		_node.MergedAt = &value
	}
	if nodes := _c.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pullrequest.AuthorTable,
			Columns: []string{pullrequest.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AuthorID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ReviewersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pullrequest.ReviewersTable,
			Columns: []string{pullrequest.ReviewersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PullRequestCreateBulk is the builder for creating many PullRequest entities in bulk.
type PullRequestCreateBulk struct {
	config
	err      error
	builders []*PullRequestCreate
}

// Save creates the PullRequest entities in the database.
func (_c *PullRequestCreateBulk) Save(ctx context.Context) ([]*PullRequest, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PullRequest, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PullRequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PullRequestCreateBulk) SaveX(ctx context.Context) []*PullRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PullRequestCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PullRequestCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
