// Code generated by ent, DO NOT EDIT.

package ent

import (
	"AvitoTechTask/internal/domain/types"
	"AvitoTechTask/pkg/ent/pullrequest"
	"AvitoTechTask/pkg/ent/user"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// PullRequest is the model entity for the PullRequest schema.
type PullRequest struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// PullRequestName holds the value of the "pull_request_name" field.
	PullRequestName string `json:"pull_request_name,omitempty"`
	// AuthorID holds the value of the "author_id" field.
	AuthorID uuid.UUID `json:"author_id,omitempty"`
	// Status holds the value of the "status" field.
	Status types.PullRequestStatus `json:"status,omitempty"`
	// AssignedReviewers holds the value of the "assigned_reviewers" field.
	AssignedReviewers []uuid.UUID `json:"assigned_reviewers,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// MergedAt holds the value of the "merged_at" field.
	MergedAt *time.Time `json:"merged_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PullRequestQuery when eager-loading is set.
	Edges                 PullRequestEdges `json:"edges"`
	user_assigned_reviews *uuid.UUID
	selectValues          sql.SelectValues
}

// PullRequestEdges holds the relations/edges for other nodes in the graph.
type PullRequestEdges struct {
	// Author holds the value of the author edge.
	Author *User `json:"author,omitempty"`
	// Reviewers holds the value of the reviewers edge.
	Reviewers []*User `json:"reviewers,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// AuthorOrErr returns the Author value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PullRequestEdges) AuthorOrErr() (*User, error) {
	if e.Author != nil {
		return e.Author, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "author"}
}

// ReviewersOrErr returns the Reviewers value or an error if the edge
// was not loaded in eager-loading.
func (e PullRequestEdges) ReviewersOrErr() ([]*User, error) {
	if e.loadedTypes[1] {
		return e.Reviewers, nil
	}
	return nil, &NotLoadedError{edge: "reviewers"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PullRequest) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pullrequest.FieldAssignedReviewers:
			values[i] = new([]byte)
		case pullrequest.FieldStatus:
			values[i] = new(sql.NullInt64)
		case pullrequest.FieldPullRequestName:
			values[i] = new(sql.NullString)
		case pullrequest.FieldCreatedAt, pullrequest.FieldMergedAt:
			values[i] = new(sql.NullTime)
		case pullrequest.FieldID, pullrequest.FieldAuthorID:
			values[i] = new(uuid.UUID)
		case pullrequest.ForeignKeys[0]: // user_assigned_reviews
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PullRequest fields.
func (_m *PullRequest) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pullrequest.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case pullrequest.FieldPullRequestName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pull_request_name", values[i])
			} else if value.Valid {
				_m.PullRequestName = value.String
			}
		case pullrequest.FieldAuthorID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field author_id", values[i])
			} else if value != nil {
				_m.AuthorID = *value
			}
		case pullrequest.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = types.PullRequestStatus(value.Int64)
			}
		case pullrequest.FieldAssignedReviewers:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field assigned_reviewers", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AssignedReviewers); err != nil {
					return fmt.Errorf("unmarshal field assigned_reviewers: %w", err)
				}
			}
		case pullrequest.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case pullrequest.FieldMergedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field merged_at", values[i])
			} else if value.Valid {
				_m.MergedAt = new(time.Time)
				*_m.MergedAt = value.Time
			}
		case pullrequest.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_assigned_reviews", values[i])
			} else if value.Valid {
				_m.user_assigned_reviews = new(uuid.UUID)
				*_m.user_assigned_reviews = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PullRequest.
// This includes values selected through modifiers, order, etc.
func (_m *PullRequest) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAuthor queries the "author" edge of the PullRequest entity.
func (_m *PullRequest) QueryAuthor() *UserQuery {
	return NewPullRequestClient(_m.config).QueryAuthor(_m)
}

// QueryReviewers queries the "reviewers" edge of the PullRequest entity.
func (_m *PullRequest) QueryReviewers() *UserQuery {
	return NewPullRequestClient(_m.config).QueryReviewers(_m)
}

// Update returns a builder for updating this PullRequest.
// Note that you need to call PullRequest.Unwrap() before calling this method if this PullRequest
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PullRequest) Update() *PullRequestUpdateOne {
	return NewPullRequestClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PullRequest entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PullRequest) Unwrap() *PullRequest {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PullRequest is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PullRequest) String() string {
	var builder strings.Builder
	builder.WriteString("PullRequest(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("pull_request_name=")
	builder.WriteString(_m.PullRequestName)
	builder.WriteString(", ")
	builder.WriteString("author_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AuthorID))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("assigned_reviewers=")
	builder.WriteString(fmt.Sprintf("%v", _m.AssignedReviewers))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.MergedAt; v != nil {
		builder.WriteString("merged_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// PullRequests is a parsable slice of PullRequest.
type PullRequests []*PullRequest
