// Code generated by ent, DO NOT EDIT.

package ent

import (
	"AvitoTechTask/internal/domain/types"
	"AvitoTechTask/pkg/ent/predicate"
	"AvitoTechTask/pkg/ent/pullrequest"
	"AvitoTechTask/pkg/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PullRequestUpdate is the builder for updating PullRequest entities.
type PullRequestUpdate struct {
	config
	hooks    []Hook
	mutation *PullRequestMutation
}

// Where appends a list predicates to the PullRequestUpdate builder.
func (_u *PullRequestUpdate) Where(ps ...predicate.PullRequest) *PullRequestUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPullRequestName sets the "pull_request_name" field.
func (_u *PullRequestUpdate) SetPullRequestName(v string) *PullRequestUpdate {
	_u.mutation.SetPullRequestName(v)
	return _u
}

// SetNillablePullRequestName sets the "pull_request_name" field if the given value is not nil.
func (_u *PullRequestUpdate) SetNillablePullRequestName(v *string) *PullRequestUpdate {
	if v != nil {
		_u.SetPullRequestName(*v)
	}
	return _u
}

// SetAuthorID sets the "author_id" field.
func (_u *PullRequestUpdate) SetAuthorID(v uuid.UUID) *PullRequestUpdate {
	_u.mutation.SetAuthorID(v)
	return _u
}

// SetNillableAuthorID sets the "author_id" field if the given value is not nil.
func (_u *PullRequestUpdate) SetNillableAuthorID(v *uuid.UUID) *PullRequestUpdate {
	if v != nil {
		_u.SetAuthorID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PullRequestUpdate) SetStatus(v types.PullRequestStatus) *PullRequestUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PullRequestUpdate) SetNillableStatus(v *types.PullRequestStatus) *PullRequestUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *PullRequestUpdate) AddStatus(v types.PullRequestStatus) *PullRequestUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetAssignedReviewers sets the "assigned_reviewers" field.
func (_u *PullRequestUpdate) SetAssignedReviewers(v []uuid.UUID) *PullRequestUpdate {
	_u.mutation.SetAssignedReviewers(v)
	return _u
}

// AppendAssignedReviewers appends value to the "assigned_reviewers" field.
func (_u *PullRequestUpdate) AppendAssignedReviewers(v []uuid.UUID) *PullRequestUpdate {
	_u.mutation.AppendAssignedReviewers(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PullRequestUpdate) SetCreatedAt(v time.Time) *PullRequestUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PullRequestUpdate) SetNillableCreatedAt(v *time.Time) *PullRequestUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetMergedAt sets the "merged_at" field.
func (_u *PullRequestUpdate) SetMergedAt(v time.Time) *PullRequestUpdate {
	_u.mutation.SetMergedAt(v)
	return _u
}

// SetNillableMergedAt sets the "merged_at" field if the given value is not nil.
func (_u *PullRequestUpdate) SetNillableMergedAt(v *time.Time) *PullRequestUpdate {
	if v != nil {
		_u.SetMergedAt(*v)
	}
	return _u
}

// ClearMergedAt clears the value of the "merged_at" field.
func (_u *PullRequestUpdate) ClearMergedAt() *PullRequestUpdate {
	_u.mutation.ClearMergedAt()
	return _u
}

// SetAuthor sets the "author" edge to the User entity.
func (_u *PullRequestUpdate) SetAuthor(v *User) *PullRequestUpdate {
	return _u.SetAuthorID(v.ID)
}

// AddReviewerIDs adds the "reviewers" edge to the User entity by IDs.
func (_u *PullRequestUpdate) AddReviewerIDs(ids ...uuid.UUID) *PullRequestUpdate {
	_u.mutation.AddReviewerIDs(ids...)
	return _u
}

// AddReviewers adds the "reviewers" edges to the User entity.
func (_u *PullRequestUpdate) AddReviewers(v ...*User) *PullRequestUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReviewerIDs(ids...)
}

// Mutation returns the PullRequestMutation object of the builder.
func (_u *PullRequestUpdate) Mutation() *PullRequestMutation {
	return _u.mutation
}

// ClearAuthor clears the "author" edge to the User entity.
func (_u *PullRequestUpdate) ClearAuthor() *PullRequestUpdate {
	_u.mutation.ClearAuthor()
	return _u
}

// ClearReviewers clears all "reviewers" edges to the User entity.
func (_u *PullRequestUpdate) ClearReviewers() *PullRequestUpdate {
	_u.mutation.ClearReviewers()
	return _u
}

// RemoveReviewerIDs removes the "reviewers" edge to User entities by IDs.
func (_u *PullRequestUpdate) RemoveReviewerIDs(ids ...uuid.UUID) *PullRequestUpdate {
	_u.mutation.RemoveReviewerIDs(ids...)
	return _u
}

// RemoveReviewers removes "reviewers" edges to User entities.
func (_u *PullRequestUpdate) RemoveReviewers(v ...*User) *PullRequestUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReviewerIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PullRequestUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PullRequestUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PullRequestUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PullRequestUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PullRequestUpdate) check() error {
	if v, ok := _u.mutation.PullRequestName(); ok {
		if err := pullrequest.PullRequestNameValidator(v); err != nil {
			return &ValidationError{Name: "pull_request_name", err: fmt.Errorf(`ent: validator failed for field "PullRequest.pull_request_name": %w`, err)}
		}
	}
	if _u.mutation.AuthorCleared() && len(_u.mutation.AuthorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PullRequest.author"`)
	}
	return nil
}

func (_u *PullRequestUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pullrequest.Table, pullrequest.Columns, sqlgraph.NewFieldSpec(pullrequest.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PullRequestName(); ok {
		_spec.SetField(pullrequest.FieldPullRequestName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(pullrequest.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(pullrequest.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AssignedReviewers(); ok {
		_spec.SetField(pullrequest.FieldAssignedReviewers, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAssignedReviewers(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, pullrequest.FieldAssignedReviewers, value)
		})
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(pullrequest.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.MergedAt(); ok {
		_spec.SetField(pullrequest.FieldMergedAt, field.TypeTime, value)
	}
	if _u.mutation.MergedAtCleared() {
		_spec.ClearField(pullrequest.FieldMergedAt, field.TypeTime)
	}
	if _u.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pullrequest.AuthorTable,
			Columns: []string{pullrequest.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pullrequest.AuthorTable,
			Columns: []string{pullrequest.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReviewersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pullrequest.ReviewersTable,
			Columns: []string{pullrequest.ReviewersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReviewersIDs(); len(nodes) > 0 && !_u.mutation.ReviewersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pullrequest.ReviewersTable,
			Columns: []string{pullrequest.ReviewersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReviewersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pullrequest.ReviewersTable,
			Columns: []string{pullrequest.ReviewersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pullrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PullRequestUpdateOne is the builder for updating a single PullRequest entity.
type PullRequestUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PullRequestMutation
}

// SetPullRequestName sets the "pull_request_name" field.
func (_u *PullRequestUpdateOne) SetPullRequestName(v string) *PullRequestUpdateOne {
	_u.mutation.SetPullRequestName(v)
	return _u
}

// SetNillablePullRequestName sets the "pull_request_name" field if the given value is not nil.
func (_u *PullRequestUpdateOne) SetNillablePullRequestName(v *string) *PullRequestUpdateOne {
	if v != nil {
		_u.SetPullRequestName(*v)
	}
	return _u
}

// SetAuthorID sets the "author_id" field.
func (_u *PullRequestUpdateOne) SetAuthorID(v uuid.UUID) *PullRequestUpdateOne {
	_u.mutation.SetAuthorID(v)
	return _u
}

// SetNillableAuthorID sets the "author_id" field if the given value is not nil.
func (_u *PullRequestUpdateOne) SetNillableAuthorID(v *uuid.UUID) *PullRequestUpdateOne {
	if v != nil {
		_u.SetAuthorID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PullRequestUpdateOne) SetStatus(v types.PullRequestStatus) *PullRequestUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PullRequestUpdateOne) SetNillableStatus(v *types.PullRequestStatus) *PullRequestUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *PullRequestUpdateOne) AddStatus(v types.PullRequestStatus) *PullRequestUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetAssignedReviewers sets the "assigned_reviewers" field.
func (_u *PullRequestUpdateOne) SetAssignedReviewers(v []uuid.UUID) *PullRequestUpdateOne {
	_u.mutation.SetAssignedReviewers(v)
	return _u
}

// AppendAssignedReviewers appends value to the "assigned_reviewers" field.
func (_u *PullRequestUpdateOne) AppendAssignedReviewers(v []uuid.UUID) *PullRequestUpdateOne {
	_u.mutation.AppendAssignedReviewers(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PullRequestUpdateOne) SetCreatedAt(v time.Time) *PullRequestUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PullRequestUpdateOne) SetNillableCreatedAt(v *time.Time) *PullRequestUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetMergedAt sets the "merged_at" field.
func (_u *PullRequestUpdateOne) SetMergedAt(v time.Time) *PullRequestUpdateOne {
	_u.mutation.SetMergedAt(v)
	return _u
}

// SetNillableMergedAt sets the "merged_at" field if the given value is not nil.
func (_u *PullRequestUpdateOne) SetNillableMergedAt(v *time.Time) *PullRequestUpdateOne {
	if v != nil {
		_u.SetMergedAt(*v)
	}
	return _u
}

// ClearMergedAt clears the value of the "merged_at" field.
func (_u *PullRequestUpdateOne) ClearMergedAt() *PullRequestUpdateOne {
	_u.mutation.ClearMergedAt()
	return _u
}

// SetAuthor sets the "author" edge to the User entity.
func (_u *PullRequestUpdateOne) SetAuthor(v *User) *PullRequestUpdateOne {
	return _u.SetAuthorID(v.ID)
}

// AddReviewerIDs adds the "reviewers" edge to the User entity by IDs.
func (_u *PullRequestUpdateOne) AddReviewerIDs(ids ...uuid.UUID) *PullRequestUpdateOne {
	_u.mutation.AddReviewerIDs(ids...)
	return _u
}

// AddReviewers adds the "reviewers" edges to the User entity.
func (_u *PullRequestUpdateOne) AddReviewers(v ...*User) *PullRequestUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReviewerIDs(ids...)
}

// Mutation returns the PullRequestMutation object of the builder.
func (_u *PullRequestUpdateOne) Mutation() *PullRequestMutation {
	return _u.mutation
}

// ClearAuthor clears the "author" edge to the User entity.
func (_u *PullRequestUpdateOne) ClearAuthor() *PullRequestUpdateOne {
	_u.mutation.ClearAuthor()
	return _u
}

// ClearReviewers clears all "reviewers" edges to the User entity.
func (_u *PullRequestUpdateOne) ClearReviewers() *PullRequestUpdateOne {
	_u.mutation.ClearReviewers()
	return _u
}

// RemoveReviewerIDs removes the "reviewers" edge to User entities by IDs.
func (_u *PullRequestUpdateOne) RemoveReviewerIDs(ids ...uuid.UUID) *PullRequestUpdateOne {
	_u.mutation.RemoveReviewerIDs(ids...)
	return _u
}

// RemoveReviewers removes "reviewers" edges to User entities.
func (_u *PullRequestUpdateOne) RemoveReviewers(v ...*User) *PullRequestUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReviewerIDs(ids...)
}

// Where appends a list predicates to the PullRequestUpdate builder.
func (_u *PullRequestUpdateOne) Where(ps ...predicate.PullRequest) *PullRequestUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PullRequestUpdateOne) Select(field string, fields ...string) *PullRequestUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PullRequest entity.
func (_u *PullRequestUpdateOne) Save(ctx context.Context) (*PullRequest, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PullRequestUpdateOne) SaveX(ctx context.Context) *PullRequest {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PullRequestUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PullRequestUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PullRequestUpdateOne) check() error {
	if v, ok := _u.mutation.PullRequestName(); ok {
		if err := pullrequest.PullRequestNameValidator(v); err != nil {
			return &ValidationError{Name: "pull_request_name", err: fmt.Errorf(`ent: validator failed for field "PullRequest.pull_request_name": %w`, err)}
		}
	}
	if _u.mutation.AuthorCleared() && len(_u.mutation.AuthorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PullRequest.author"`)
	}
	return nil
}

func (_u *PullRequestUpdateOne) sqlSave(ctx context.Context) (_node *PullRequest, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pullrequest.Table, pullrequest.Columns, sqlgraph.NewFieldSpec(pullrequest.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PullRequest.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pullrequest.FieldID)
		for _, f := range fields {
			if !pullrequest.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pullrequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PullRequestName(); ok {
		_spec.SetField(pullrequest.FieldPullRequestName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(pullrequest.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(pullrequest.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AssignedReviewers(); ok {
		_spec.SetField(pullrequest.FieldAssignedReviewers, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAssignedReviewers(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, pullrequest.FieldAssignedReviewers, value)
		})
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(pullrequest.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.MergedAt(); ok {
		_spec.SetField(pullrequest.FieldMergedAt, field.TypeTime, value)
	}
	if _u.mutation.MergedAtCleared() {
		_spec.ClearField(pullrequest.FieldMergedAt, field.TypeTime)
	}
	if _u.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pullrequest.AuthorTable,
			Columns: []string{pullrequest.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pullrequest.AuthorTable,
			Columns: []string{pullrequest.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReviewersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pullrequest.ReviewersTable,
			Columns: []string{pullrequest.ReviewersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReviewersIDs(); len(nodes) > 0 && !_u.mutation.ReviewersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pullrequest.ReviewersTable,
			Columns: []string{pullrequest.ReviewersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReviewersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pullrequest.ReviewersTable,
			Columns: []string{pullrequest.ReviewersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PullRequest{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pullrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
