// Code generated by ent, DO NOT EDIT.

package ent

import (
	"AvitoTechTask/internal/domain/schema"
	"AvitoTechTask/pkg/ent/pullrequest"
	"AvitoTechTask/pkg/ent/team"
	"AvitoTechTask/pkg/ent/user"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	pullrequestFields := schema.PullRequest{}.Fields()
	_ = pullrequestFields
	// pullrequestDescPullRequestName is the schema descriptor for pull_request_name field.
	pullrequestDescPullRequestName := pullrequestFields[1].Descriptor()
	// pullrequest.PullRequestNameValidator is a validator for the "pull_request_name" field. It is called by the builders before save.
	pullrequest.PullRequestNameValidator = pullrequestDescPullRequestName.Validators[0].(func(string) error)
	// pullrequestDescAssignedReviewers is the schema descriptor for assigned_reviewers field.
	pullrequestDescAssignedReviewers := pullrequestFields[4].Descriptor()
	// pullrequest.DefaultAssignedReviewers holds the default value on creation for the assigned_reviewers field.
	pullrequest.DefaultAssignedReviewers = pullrequestDescAssignedReviewers.Default.([]uuid.UUID)
	// pullrequestDescCreatedAt is the schema descriptor for created_at field.
	pullrequestDescCreatedAt := pullrequestFields[5].Descriptor()
	// pullrequest.DefaultCreatedAt holds the default value on creation for the created_at field.
	pullrequest.DefaultCreatedAt = pullrequestDescCreatedAt.Default.(func() time.Time)
	// pullrequestDescID is the schema descriptor for id field.
	pullrequestDescID := pullrequestFields[0].Descriptor()
	// pullrequest.DefaultID holds the default value on creation for the id field.
	pullrequest.DefaultID = pullrequestDescID.Default.(func() uuid.UUID)
	teamFields := schema.Team{}.Fields()
	_ = teamFields
	// teamDescTeamName is the schema descriptor for team_name field.
	teamDescTeamName := teamFields[0].Descriptor()
	// team.TeamNameValidator is a validator for the "team_name" field. It is called by the builders before save.
	team.TeamNameValidator = teamDescTeamName.Validators[0].(func(string) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[1].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescIsActive is the schema descriptor for is_active field.
	userDescIsActive := userFields[2].Descriptor()
	// user.DefaultIsActive holds the default value on creation for the is_active field.
	user.DefaultIsActive = userDescIsActive.Default.(bool)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
